[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pkg_a"
version = "0.0.1"
description = "Mycorp's fancy library"
authors = ["Tweag <hello@tweag.io>"]
packages = [{ include = "../pkg_a" }]


[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "1.0.1"

[tool.poetry.group.dev.dependencies]
pyright = "1.1.380"
ruff = "0.6.4"
pytest = "8.3.3"
pytest-cov = "5.0.0"
factory-boy = "3.3.1"
ipython = "8.27.0"
taskipy = "1.13.0"
dunamai = "1.7.0"
